### ISSUE TITLE
#002 - [Frontend] Criar aplicação frontend básica.

### ISSUE THREAD

**Issue by JeovaJrAguiar** [JeovaJrAguiar/show-do-milhao#2]
### Objetivo:
Criar aplicação base em react.

### Descrição:
Necessário criar a aplicação em React, para que os outros processos sejam iniciados.

### Observações:
No curso disponibilizado para o @joaooctaviooo tem as informações necessárias para a operação.

### Anexo(s):
N/A

**Comment by joaooctaviooo** [comment]
Resultado esperado:
Criar aplicação base react

Resultado entregue:
Foi criada a aplicação básica como solicitado.

Observações:
N/A

Anexo(s):
N/A

**Comment by JeovaJrAguiar** [comment]
Review realizada. Sem alterações.

Segue para PR. Bom trabalho.

**Comment by joaooctaviooo** [comment]
❤️
